name: master_deploy_work

on:
  push:
    branches:
      - master     

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
      
      #- name: Build
      #  run: aws s3 rm s3://svc3.nuriblock.com  --recursive
 
      # below S3  is created by JCW 2022. 08 - edit the resoucre   
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp  --recursive  --region ap-northeast-2  . s3://svc3.nuriblock.com   --recursive  --exclude ".git/*"  --exclude "reference/*"

      # below distribution-id is created by JCW 2022. 08 - edit the resoucre  
      - name: CDN_INVALIDATE
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws cloudfront create-invalidation --distribution-id  E23DQUPFR317G3  --paths "/*"   --region ap-northeast-2    
